autentikasi/urls.py
from django.urls import path
from . import views

app_name = 'autentikasi'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

landing/urls.py
from django.urls import path
from . import views

app_name = 'landing'

urlpatterns = [
    path('', views.katalog, name='katalog'),
]

my_profile/urls.py
from django.urls import path
from . import views

app_name = 'my_profile'

urlpatterns = [
    path('my-profile/index/', views.index, name='index'),
    path('my-profile/edit/', views.edit_profile, name='edit_profile'),
]

pet_shelter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('autentikasi.urls')),
    path('', include(('landing.urls', 'landing'), namespace='landing')),
    path('', include(('autentikasi.urls', 'autentikasi'), namespace='autentikasi')),
    path('', include(('other_profile.urls', 'other_profile'), namespace='other_profile')),
    path('', include('my_profile.urls')),
]

my_profile/models.py
from django.db import models

# Create your models here.

my_profile/forms.py
from django import forms
from django.contrib.auth import get_user_model
import re

User = get_user_model()

class EditProfileForm(forms.Form):
    username = forms.CharField(label='Username', widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Username',
    }))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'placeholder': 'Email address',
    }))
    address = forms.CharField(label='Address', widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Home address',
    }))
    phone = forms.CharField(label='Phone Number', widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': '+628123456789',
    }))
    password = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Password',
    }))
    confirm_password = forms.CharField(label="Confirm password", widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Confirm your password',
    }))

    def clean(self):
        cleaned_data = self.cleaned_data
        password_one = cleaned_data.get('password')
        password_two = cleaned_data.get('confirm_password')
        print(f"Username : {cleaned_data.get('username')}")
        print(f"Password : {password_one}")
        print(f"Confirm Password : {password_two}")
        if (password_one != password_two):
            raise forms.ValidationError("Passwords don't match")
        return cleaned_data

    def clean_username(self):
        username = self.cleaned_data.get('username')
        qs = User.objects.filter(username=username)
        if (qs.exists()):
            raise forms.ValidationError("The username you've chosen is unavailable.")
        return username

    def clean_email(self):
        email_address = self.cleaned_data.get('email')
        qs = User.objects.filter(email=email_address)
        if (qs.exists()):
            raise forms.ValidationError("The email address you've chosen is already registered.")
        return email_address

    def clean_phone(self):
        phone_pattern = re.compile(r'^\+\d{10,15}$')
        phone_number = self.cleaned_data.get('phone')
        if (not phone_pattern.match(phone_number)):
            raise forms.ValidationError("Phone number must be entered in the format: '+999999999'. 10-15 digits is allowed.")
        return phone_number

my_profile/views.py
from django.shortcuts import redirect, render
from .forms import EditProfileForm
from django.contrib.auth import get_user_model
from django.contrib.auth import authenticate, login as auth_login

User = get_user_model()


# Create your views here.
def index(request):
    return render(request, "my_profile.html")


def edit_profile(request):
    form = EditProfileForm(request.POST or None)
    if form.is_valid():
        cleaned_form = form.cleaned_data
        username = cleaned_form.get("username")
        email = cleaned_form.get("email")
        password = cleaned_form.get("password")
        address = cleaned_form.get("address")
        phone_num = cleaned_form.get("phone")

        user = User.objects.get(username=request.user.username)

        if len(username) != 0:
            user.username = username
        if len(email) != 0:
            user.email = email
        if len(password) != 0:
            user.set_password(password)
        if len(address) != 0:
            user.home_address = address
        if len(phone_num) != 0:
            user.phone_number = phone_num

        user.save()
        print(f"Username : {user.username}")
        print(f"Password : {user.password}")
        print(f"Email : {user.email}")
        user = authenticate(request, username=username, password=password)
        auth_login(request, user)
        return redirect('/my-profile/index')

    return render(request, "form_edit_profile.html", context={'form': form})

my_profile/templates/form_edit_profile.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- <link rel="stylesheet" href="{% static './navbar.css' %}"> -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <style>
        .topnav {
            background-color: #BD5555;
        }

        .teksnav {
            color: #FFFFFF;
            margin-right: 15px;
        }

        .home {
            font-size: 30px;
        }

        .teksnav:hover {
            color: #1A1A2E;
        }

        .navbar-link:hover {
            text-decoration: none;
        }

        .kanan {
            margin-left: auto;
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark topnav">
        <a class="navbar-link" href="{% url 'landing:katalog' %}">
            <h5 class="home teksnav">Pet Shelter</h5>
        </a>

        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav kanan">
                <!-- {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'my_profile:index' %}">
                    <h5 class="teksnav">{{user.username}}</h5>
                </a>

                <a class="nav-link" href="{% url 'autentikasi:logout'%}">
                    <h5 class="teksnav">Keluar</h5>
                </a>

                {% else %}
                <a class="nav-link" href="{% url 'autentikasi:login'%}">
                    <h5 class="teksnav">Masuk</h5>
                </a>

                <a class="nav-link" href="{% url 'autentikasi:register'%}">
                    <h5 class="teksnav">Daftar</h5>
                </a>
                {% endif %} -->
            </div>
        </div>
    </nav>

    {% csrf_token %}
    <div class="row m-5 justify-content-center">
        <div class="col-md-8 col-sm-8">
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Submit</button>
                <button type="button" class="btn btn-secondary">
                    <a href="{% url 'my_profile:index' %}" style="text-decoration: none; color: white;">Cancel</a>
                </button>
            </form>
        </div>
    </div>
</body>

</html>

my_profile/templates/my_profile.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- <link rel="stylesheet" href="{% static './styles.css' %}">
    <link rel="stylesheet" href="{% static './navbar.css' %}"> -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title>My Profile</title>
    <style>
        .topnav {
            background-color: #BD5555;
        }

        .teksnav {
            color: #FFFFFF;
            margin-right: 15px;
        }

        .home {
            font-size: 30px;
        }

        .teksnav:hover {
            color: #1A1A2E;
        }

        .navbar-link:hover {
            text-decoration: none;
        }

        .kanan {
            margin-left: auto;
        }
        p {
            font-weight: bold;
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark topnav">
        <a class="navbar-link" href="{% url 'landing:katalog' %}">
            <h5 class="home teksnav">Pet Shelter</h5>
        </a>

        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav kanan">
                {% if user.is_authenticated %}
                <!-- <a class="nav-link" href="{% url 'my_profile:index' %}">
                    <h5 class="teksnav">{{user.username}}</h5>
                </a> -->

                <a class="nav-link" href="{% url 'autentikasi:logout'%}">
                    <h5 class="teksnav">Keluar</h5>
                </a>

                {% else %}
                <a class="nav-link" href="{% url 'autentikasi:login'%}">
                    <h5 class="teksnav">Masuk</h5>
                </a>

                <a class="nav-link" href="{% url 'autentikasi:register'%}">
                    <h5 class="teksnav">Daftar</h5>
                </a>
                {% endif %}
            </div>
        </div>
    </nav>

    {% if user.is_authenticated %}
    <div class="text-center mt-5">
        <p>Username : {{ user.username }}</p>
        <p>Email : {{ user.email }}</p>
        <p>Address : {{ user.home_address }}</p>
        <p>Phone Number : {{ user.phone_number }}</p>
        <a href="{% url 'my_profile:edit_profile' %}" style="text-decoration: none; color: white;">
            <button type="button" class="btn btn-primary mx-auto d-block">Edit Profile</button>
        </a>
    </div>
    {% endif %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>

</html>