landing/urls.py
from django.urls import path
from . import views

app_name = 'landing'

urlpatterns = [
    path('', views.katalog, name='katalog'),
]

other_profile/urls.py
from django.urls import path
from . import views

app_name = 'other_profile'

urlpatterns = [
    path('<str:username>/', views.profile, name='profile'),
    path('<str:username>/report/', views.report_user, name='report_user'),
]

pet_shelter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('autentikasi.urls')),
    path('', include(('landing.urls', 'landing'), namespace='landing')),
    path('', include(('autentikasi.urls', 'autentikasi'), namespace='autentikasi')),
    path('', include(('other_profile.urls', 'other_profile'), namespace='other_profile')),
    path('', include('my_profile.urls')),
]

other_profile/models.py
from django.db import models
from django.contrib.auth import get_user_model

# Create your models here.
class Report(models.Model):
    reported_user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='reported_user')
    reason = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Report #{self.id} -> {self.reported_user.username}'

other_profile/forms.py
from django import forms

class ReportForm(forms.Form):
    reason = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Tell me why!',
        'required': True,
    }))

other_profile/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import get_user_model
from .forms import ReportForm
from .models import Report

User = get_user_model()

# Create your views here.
def profile(request, username):
    user = get_object_or_404(User, username=username)
    context = {
        'user': user
    }
    return render(request, 'profile.html', context)

def report_user(request, username):
    reported_user = get_object_or_404(User, username=username)
    
    if request.method == 'POST':
        form = ReportForm(request.POST)
        if form.is_valid():
            reason = form.cleaned_data['reason']
            Report.objects.create(
                reported_user=reported_user,
                reason=reason,
            )
            context = {'user': reported_user}
            return render(request, 'profile.html', context)
    else:
        form = ReportForm()
        
    context = {'form': form, 'reported_user': reported_user}
    return render(request, 'report.html', context)

other_profile/templates/profile.html
{% load static %}

<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <title>User Profile</title>

        <style>
            .submit {
                margin-top: 15px;
                border: none;
                width: 100px;
                font-size: 20px;
                background-color: #BD5555;
                color: #F3F3F3;
                border-radius: 10px;
            }
            .submit:hover {
                background-color: #920003;
            }
        </style>
    </head>

    {% include "navbar.html" %}
    <body style="background-color: #F3F3F3;">
        <div class="row justify-content-center">
            <div class="col text-center">
                <h4>Username: {{ user.username }}</h4>
                <h4>Email: {{ user.email }}</h4>
                <h4>Home Address: {{ user.home_address }}</h4>
                <h4>Phone Number: {{ user.phone_number }}</h4>
            </div>
        </div>

        <div class="row m-5 justify-content-center">
            <div class="col-sm-4 text-center">
                <a href="{% url 'other_profile:report_user' username=user.username %}">
                    <button class="submit" type="submit">Report</button>
                </a>
            </div>
        </div>

        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

other_profile/templates/report.html
{% load static %}

<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <title>User Profile</title>

        <style>
            .submit {
                margin-top: 15px;
                border: none;
                width: 100px;
                font-size: 20px;
                background-color: rgb(52, 56, 187);
                color: #F3F3F3;
                border-radius: 10px;
            }
            .submit:hover {
                background-color: rgb(12, 19, 231);
            }
            .cancel {
                background-color: #BD5555;
            }
            .cancel:hover {
                background-color: #920003;
            }
        </style>
    </head>

    {% include "navbar.html" %}
    <body style="background-color: #F3F3F3;">
        <div class="row justify-content-center">
            <div class="col text-center">
                <form method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="row m-5 justify-content-center">
                        <div class="col-sm-4 text-center">
                            <a href="{% url 'other_profile:profile' username=reported_user.username %}">
                                <button class="cancel submit" type="button">Cancel</button>
                            </a>
                        </div>
            
                        <div class="col-sm-4 text-center">
                            <a href="{% url 'landing:katalog' %}">
                                <button class="submit" type="submit">Submit</button>
                            </a>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>